; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1 ; Configuração genérica padrão para o chip S3
framework = arduino
monitor_speed = 115200

; Configurações vitais para o ESP32-S3 reconhecer a Serial nativa
build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

; Substitua pelas portas COM reais da sua bancada
upload_port = COM5   
monitor_port = COM5

lib_deps =
    https://github.com/tzapu/WiFiManager.git
    bblanchon/ArduinoJson @ ^7.0.4
    paulstoffregen/OneWire @ ^2.3.8
    milesburton/DallasTemperature @ ^3.9.1